# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  - package-ecosystem: "pip"
    # Look for `build.gradle` in the `root` directory
    directory: "/library/"
    # Check for updates once weekly
    schedule:
        interval: "weekly"
        ignore:
            # Ignore updates to packages that start 'aws'
            # Wildcards match zero or more arbitrary characters
            - dependency-name: "flask*"
            - dependency-name: org.apache:maven:*

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
