---
# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  - package-ecosystem: pip
    # Look for `build.gradle` in the `root` directory
    directory: /
    # Check for updates once weekly
    schedule:
      interval: monthly
    allow:
      # Allow only direct updates for
      # Django and any packages starting "django"
      - dependency-name: django*
        dependency-type: direct
      # Allow only production updates for Sphinx
      - dependency-name: sphinx
        dependency-type: production
    ignore:
      # For Lodash, ignore all updates
      - dependency-name: lodash
      - dependency-name: flask*
      - dependency-name: org.apache:maven:*
    # Allow up to 10 open pull requests for pip dependencies
    open-pull-requests-limit: 10

  - package-ecosystem: pip
    directory: "/playbooks/files/python/"
    schedule:
      interval: "monthly"
    labels: [ ]
    ignore:
      - dependency-name: "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  # Enable version updates for npm
  - package-ecosystem: npm
    # Look for `package.json` and `lock` files in the `root` directory
    directory: /
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: "/directory-to-exclude"
    schedule:
      interval: "monthly"
    labels: [ ]
    ignore:
      - dependency-name: "*"

  # Enable version updates for Docker
  - package-ecosystem: docker
    # Look for a `Dockerfile` in the `root` directory
    directory: /
    # Check for updates once a week
    schedule:
      interval: weekly
