---
stages:
  - static
  - build
  - test
  - release
  - deploy

include:
  - project: jusmundi-group/infrastructure/ci-templates
    ref: feature-data
    file: "/templates/default.gitlab-ci.yml"

  - project: jusmundi-group/infrastructure/ci-templates
    ref: feature-data
    file: "/templates/docker-build.gitlab-ci.yml"

  - project: jusmundi-group/infrastructure/ci-templates
    ref: feature-data
    file: "/templates/deploy-nomad.gitlab-ci.yml"

  - project: jusmundi-group/infrastructure/ci-templates
    ref: feature-data
    file: "/templates/test-python.gitlab-ci.yml"

variables:
  # APP: ${CI_PROJECT_NAME}
  # CI_REGISTRY: registry.gitlab.com
  OCI_REGISTRY: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}
  # CODE_QUALITY_DISABLED: "true"
  SECRET_DETECTION_IMAGE_SUFFIX: "-fips"
  SEMGREP_APP_TOKEN: $SEMGREP_APP_TOKEN
  CI_IMAGE_NAME: nabla/ansible-jenkins-slave-docker
  CI_IMAGE_TAG: latest
  CI_IMAGE: ${CI_IMAGE_NAME}:${CI_IMAGE_TAG}

default:
  image: $CI_IMAGE

mega_linter:
  extends: .mega_linter_common
  allow_failure: true

biscuitcutter:
  stage: static
  tags:
    - docker
  script:
    - ./biscuitcutter.sh
  rules:
    - !reference [.default_rules, rules]

lint_flake8:
  image: $CI_IMAGE
  needs: ["biscuitcutter"]
  extends: .lint-flake8
  stage: static
  tags:
    - docker
  variables:
    DEFAULT_FLAKE8_TARGET: "test"
    DEFAULT_FLAKE8_ARGS: "--max-line-length=88 --max-complexity=10"
  before_script:
    - curl https://bootstrap.pypa.io/get-pip.py | python3
    - pip install flake8
  script: python -m flake8 --version

docker-build:
  extends: .docker-build
  tags:
    - jusmundi-nomad-runner
  # services:
  #  - name: docker:dind
  #    entrypoint: ["env", "-u", "DOCKER_HOST"]
  #    command: ["dockerd-entrypoint.sh"]
  variables:
    # CONTAINER_SCANNING_GITLAB_CODEQUALITY_TEMPLATE_DISABLE: "true"
    TRIVY_FILESYTEM_EXIT_ON_FAILURE: 0
    # yamllint disable-line rule:line-length
    TRIVY_ARGS: "--skip-dirs .direnv --skip-dirs /home/ubuntu/go/ --skip-dirs /home/ubuntu/node_modules/ --skip-dirs /home/runner/work/trivy/ --skip-dirs /usr/local/lib/python3.8/dist-packages/ansible/galaxy/ --skip-dirs /home/ubuntu/.local/lib/python3.8/site-packages/ansible --skip-dirs /home/ubuntu/.local/lib/python3.8/site-packages/awscli/ --skip-dirs /home/ubuntu/.local/share/virtualenvs/ --skip-dirs /home/ubuntu/.local/lib/python3.8/site-packages/rsa/ --skip-dirs /home/ubuntu/.local/lib/python3.8/site-packages/botocore/data/ --skip-dirs /usr/lib/node_modules/ --skip-files /usr/local/bin/container-structure-test --skip-files /usr/local/go/src/crypto/elliptic/internal/fiat/Dockerfile --ignore-policy avd.aquasec.com/appshield/ds002"

docker-test:
  needs: ["docker-build"]
  stage: test
  tags:
    - jusmundi-nomad-runner
  # services:
  #  - name: docker:dind
  #    entrypoint: ["env", "-u", "DOCKER_HOST"]
  #    command: ["dockerd-entrypoint.sh"]
  script:
    - make test-cst
    - make test-dive-ci
  rules:
    - !reference [.default_rules, rules]

docker-release:
  extends: .docker-deploy-latest-gitlab
  needs: ["docker-build"]
