---
language: python
python:
  - 2.7
#  - 3.3
#  - 3.4
#  - 3.5
cache:
  directories:
    - $HOME/.cache/pip
env:
#  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.4.1.0
#  - ANSIBLE_VERSION=2.3.1.0
#  - ANSIBLE_VERSION=2.2.2.0  
cache: bundler
#sudo: false
sudo: required
dist: trusty

branches:
  only:
    - master

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install curl
 - sudo apt-get install -qq python-apt python-pycurl

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

  # Update Ansible submodule.
  - git pull && git submodule init && git submodule update && git submodule status
  - git submodule foreach git checkout master

  - ansible-galaxy install -r requirements.yml -p ./roles/ --ignore-errors
    
script:
  # Check ansible version
  - ansible --version
  
  # Add ansible.cfg to pick up roles path.
  #- "{ echo '[defaults]'; echo 'roles_path = ./roles'; } >> ansible.cfg"
  #- export ANSIBLE_ROLES_PATH="../"

  # Prepare tests
  #- echo localhost > hosts

  # Check syntax
  # Check the role/playbook's syntax.
  - ansible-playbook --syntax-check -i hosts jenkins-slave-docker.yml --connection=local -e "python_versions=[2.7, 3.5]"

  # First run
  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i hosts jenkins-slave-docker.yml --connection=local --sudo -vvvv -e "python_versions=[2.7, 3.5]"

  # Second run Idempotence test
  # Run the role/playbook again, checking to make sure it's idempotent.
#  - >
#    ansible-playbook -i hosts workstation.yml --connection=local --sudo
#    | grep -q 'changed=0.*failed=0'
#    && (echo 'Idempotence test: pass' && exit 0)
#    || (echo 'Idempotence test: fail' && exit 1)

#  - sudo /etc/init.d/jenkins status || exit 1
#  - sudo /etc/init.d/nexus status || exit 1
#  - sudo /etc/init.d/mon status || exit 1

  # Test whether kibana is running correctly.
#  - curl http://localhost/

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    recipients:
      - alban.andrieu@nabla.mobi
#      - other@example.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always
