---
language: python
python:
  - 2.7
#  - 3.3
#  - 3.4
#  - 3.5
cache:
  directories:
    - $HOME/.cache/pip
env:
  - ANSIBLE_VERSION=2.3.1.0
cache: bundler
#sudo: false
sudo: required
dist: trusty
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install curl
 - sudo apt-get install -qq python-apt python-pycurl

install:
  # Install Ansible.
  - sudo pip install ansible==$ANSIBLE_VERSION

  # Add ansible.cfg to pick up roles path.
#  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

  # Update Ansible submodule.
  - git pull && git submodule init && git submodule update && git submodule status
  - git submodule foreach git checkout master
  
  # Install dependencies.
  #- ansible-galaxy install alban.andrieu.subversion
  #- ansible-galaxy install alban.andrieu.xvbf
  #- git clone https://github.com/AlbanAndrieu/Stouts.python.git python
  #- git clone https://github.com/AlbanAndrieu/ansible-role-ntp.git geerlingguy.ntp
  #- git clone https://github.com/AlbanAndrieu/ansible-locale.git locale
  #- git clone https://github.com/AlbanAndrieu/ansible-hostname.git alban.andrieu.hostname
  #- git clone https://github.com/AlbanAndrieu/ansible-util.git silpion.util
  #- git clone https://github.com/AlbanAndrieu/ansible-lib silpion.lib
  #- git clone https://github.com/AlbanAndrieu/ansible-java.git java
  #- git clone https://github.com/AlbanAndrieu/ansible-common.git alban.andrieu.common
  #- git clone https://github.com/AlbanAndrieu/ansible-subversion.git alban.andrieu.subversion
  #- git clone https://github.com/AlbanAndrieu/ansible-role-git.git geerlingguy.git
  #- git clone https://github.com/AlbanAndrieu/ansible-cmake.git alban.andrieu.cmake
  #- git clone https://github.com/AlbanAndrieu/ansible-cpp.git alban.andrieu.cpp
  #- git clone https://github.com/AlbanAndrieu/ansible-xvbf alban.andrieu.xvbf
  #- git clone https://github.com/AlbanAndrieu/ansible-selenium alban.andrieu.selenium
  #- git clone https://github.com/AlbanAndrieu/ansible-maven.git maven
  ##- git clone https://github.com/AlbanAndrieu/ansible-java.git java
  #- git clone https://github.com/AlbanAndrieu/devbox.chrome.git chrome
  ##- git clone https://github.com/AlbanAndrieu/ansible-role-security.git security
  #- git clone https://github.com/AlbanAndrieu/ansible-nodejs.git nodejs
  #- git clone https://github.com/AlbanAndrieu/ansible-tomcat alban.andrieu.tomcat
  #- git clone https://github.com/AlbanAndrieu/ansible-jboss alban.andrieu.jboss
  
  - ansible-galaxy install -r requirements.yml -p ./roles/ --ignore-errors
    
script:
  # Check ansible version
  - sudo ansible --version

  # Prepare tests
#  - echo localhost > inventory

  # Check syntax
  # Check the role/playbook's syntax.
  - sudo ansible-playbook --syntax-check -i hosts jenkins-slave-docker.yml --connection=local

  # First run
  # Run the role/playbook with ansible-playbook.
  - sudo ansible-playbook -i hosts jenkins-slave-docker.yml --connection=local --sudo

  # Second run Idempotence test
  # Run the role/playbook again, checking to make sure it's idempotent.
#  - >
#    ansible-playbook -i hosts workstation.yml --connection=local --sudo
#    | grep -q 'changed=0.*failed=0'
#    && (echo 'Idempotence test: pass' && exit 0)
#    || (echo 'Idempotence test: fail' && exit 1)

#  - sudo /etc/init.d/jenkins status || exit 1
#  - sudo /etc/init.d/nexus status || exit 1
#  - sudo /etc/init.d/mon status || exit 1

  # Test whether kibana is running correctly.
#  - curl http://localhost/

notifications:
  email:
    recipients:
      - alban.andrieu@nabla.mobi
#      - other@example.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always
