---
language: python
python: "2.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install curl
 - sudo apt-get install -qq python-apt python-pycurl

install:
  # Install Ansible.
#  - pip install ansible>=1.6.0
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
#  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

# Install required dependencies.
#  - git clone https://github.com/AlbanAndrieu/ansible-subversion.git alban.andrieu.subversion
#  - git clone https://github.com/AlbanAndrieu/ansible-role-git.git geerlingguy.git
#  - git clone https://github.com/AlbanAndrieu/ansible-jenkins-slave.git alban.andrieu.jenkins-slave
#  - git clone https://github.com/AlbanAndrieu/ansible-xvbf alban.andrieu.xvbf

  # Update Ansible submodule.
  - git pull && git submodule init && git submodule update && git submodule status
  - git submodule foreach git checkout master
  
  #- git clone https://github.com/Stouts/Stouts.python.git python
  #- git clone https://github.com/debops/ansible-role-ansible.git ansible
  #- git clone https://github.com/geerlingguy/ansible-role-ntp.git geerlingguy.ntp
  #- git clone https://github.com/AlbanAndrieu/ansible-locale.git locale
  #- git clone https://github.com/AlbanAndrieu/ansible-hostname.git alban.andrieu.hostname
  #- git clone https://github.com/AlbanAndrieu/ansible-java.git java
  #- git clone https://github.com/AlbanAndrieu/ansible-common.git alban.andrieu.common
  #- git clone https://github.com/AlbanAndrieu/ansible-subversion.git alban.andrieu.subversion
  #- git clone https://github.com/AlbanAndrieu/ansible-role-git.git geerlingguy.git
  #- git clone https://github.com/AlbanAndrieu/ansible-cmake.git alban.andrieu.cmake
  #- git clone https://github.com/AlbanAndrieu/ansible-cpp.git alban.andrieu.cpp    
  #- git clone https://github.com/AlbanAndrieu/ansible-xvbf alban.andrieu.xvbf
  #- git clone https://github.com/AlbanAndrieu/ansible-selenium alban.andrieu.selenium
  #- git clone https://github.com/AlbanAndrieu/ansible-maven.git maven
  ##- git clone https://github.com/AlbanAndrieu/ansible-java.git java
  #- git clone https://github.com/AlbanAndrieu/devbox.chrome.git chrome
  ##- git clone https://github.com/AlbanAndrieu/ansible-role-security.git security
  #- git clone https://github.com/AlbanAndrieu/ansible-nodejs.git nodejs
  #- git clone https://github.com/AlbanAndrieu/ansible-tomcat alban.andrieu.tomcat
  #- git clone https://github.com/AlbanAndrieu/ansible-jboss alban.andrieu.jboss
    
script:
  # Check ansible version
  - ansible --version

  # Prepare tests
#  - echo localhost > inventory

  # Check syntax
  # Check the role/playbook's syntax.
  - ansible-playbook --syntax-check -i hosts jenkins-slave-docker.yml --connection=local

  # First run
  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i hosts jenkins-slave-docker.yml --connection=local --sudo

  # Second run Idempotence test
  # Run the role/playbook again, checking to make sure it's idempotent.
#  - >
#    ansible-playbook -i hosts workstation.yml --connection=local --sudo
#    | grep -q 'changed=0.*failed=0'
#    && (echo 'Idempotence test: pass' && exit 0)
#    || (echo 'Idempotence test: fail' && exit 1)

#  - sudo /etc/init.d/jenkins status || exit 1
#  - sudo /etc/init.d/nexus status || exit 1
#  - sudo /etc/init.d/mon status || exit 1

  # Test whether kibana is running correctly.
#  - curl http://localhost/
