language: python
python:
- 2.7
cache: bundler
env:
  matrix:
  - ANSIBLE_VERSION=2.4.1.0
  global:
    secure: MD73NCVzctbVmi2QnQtwtH/ISXN2K0alsLbixoaXl7gr3XvTB4sYB0u+KKtPV46jbeAlQqTRObPfQouPrsLsiNDYcpuN0I5bKsn3TTs4ZHIkD0I2Q9Wh3qNM2fYf9mw3ZUhvXVTEod0W7jzkVGb6kitRCJj8rioKKzvE/YdVsG4=
sudo: required
dist: trusty
branches:
  only:
  - master
before_install:
- sudo apt-get update -qq
- sudo apt-get install curl
- sudo apt-get install -qq python-apt python-pycurl
install:
- if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install
  ansible==$ANSIBLE_VERSION; fi
- if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi
- git pull && git submodule init && git submodule update && git submodule status
- git submodule foreach git checkout master
- ansible-galaxy install -r requirements.yml -p ./roles/ --ignore-errors
script:
- ansible --version
- ansible-playbook --syntax-check -i hosts jenkins-slave-docker.yml --connection=local
  -e "python_versions=[2.7]"
- ansible-playbook -i hosts jenkins-slave-docker.yml --connection=local --sudo -vvvv
  -e "python_versions=[2.7]"
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    recipients:
    - alban.andrieu@nabla.mobi
    on_success:
    - always|never|change
    on_failure:
    - always|never|change
