---
#ansible-playbook -i hosts -c local -v jenkins-slave.yml -vvvv | tee setup.log
#ansible-playbook jenkins-slave.yml -i hosts -vvvv --ask-sudo-pass --sudo

- hosts: all
  gather_facts: true
  tasks:
    - name: group hosts by distribution
      group_by: key="{{ ansible_distribution }}-{{ ansible_distribution_version }}"

- hosts: RedHat-7*:RedHat-6*:RedHat-5*:CentOS-7*:CentOS-6*:Ubuntu-17*:Ubuntu-16*:Ubuntu-15*:Ubuntu-14*:Ubuntu-13*:Ubuntu-12*
  gather_facts: false
  tasks:
    - name: group hosts for supported distributions
      group_by: key="supported"

- hosts: "!supported"
  gather_facts: false
  tasks:
    - name: fail for unsupported distribution
      fail: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}
                 is not a supported OS for a Tower installation.  Supported
                 OSes include Red Hat Enterprise Linux 6/7/5, CentOS 6/7, or
                 Ubuntu 12.04/12.04/14.04/16.04/17.04."
    - debug: msg="Version {{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_architecture }}"

- name: Apply common configuration to all jenkins slaves
  hosts: jenkins-slaves
  become: yes
  remote_user: root

  roles:
    - alban.andrieu.jenkins-slave

  vars:
    docker_files_enable: yes
    docker_files_generated_directory: "./"
    shell_git:
      # Additional properties: 'shell_git_machine, shell_git_login, shell_git_email, shell_git_password, shell_git_name, shell_git_path, shell_git_ssl'.
       - {
         shell_git_machine: '82.231.208.223',
         shell_git_login: 'AlbanAndrieu',
         shell_git_email: 'alban.andrieu@free.fr',
         shell_git_password: 'microsoft',
         # Optional.
         shell_git_name: 'Andrieu, Alban',
         shell_git_path: '/usr/bin',
         shell_git_ssl: false
       }        
    subversion_rabbitvcs_enabled: no
    subversion_diff_enabled: no
    # tomcat_started_check_enable: yes does not work on docker hub
    tomcat_started_check_enable: no
    #home_url: "http://home.nabla.mobi"
    nexus_url: "http://home.nabla.mobi:8085"
    bower_url: "http://home.nabla.mobi:5678"
    npm_nexus_npm_url: ""
    #npm_phantomjs_cdnurl: "http://home.nabla.mobi:7070/download/phantomjs"
    jenkins_home: "/home/jenkins"
    jenkins_group: docker
    jenkins_ssh_authorized_keys_fingerprints:   # Set known authorized keys for ssh
    # Alban Andrieu
      - "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAIEAio3SOQ9yeK6QfKqSFNKyTasuzjStxWevG1Vz1wgJIxPF+KB0XoMAPD081J+Bzj2LCDRSWisNv2L4xv2jbFxW/Pl7NEakoX47eNx3U+Dxaf+szeWBTryYcDUGkduLV7G8Qncm0luIFd+HDIe/Qir1E2f56Qu2uuBNE6Tz5TFt1vc= Alban"
    jenkins_ssh_fingerprints: # Set known hosts for ssh
      - "bitbucket.org,131.103.20.167 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw=="
      - "github.com,204.232.175.90 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
      - "[scm-git-eur.misys.global.ad]:7999,[10.21.200.140]:7999 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCP8ZkWwD/REuQ+jYwWGKANklOidkkmgbHDlJbQQkjVSW2iLnuldYcvLfqcu3HNfSBfJ7YH+iyeZKUDYw2kGgXymbVENTaBCfOCu/ztrnHWUn7zUFCWP12WxgzNQ7InVN+YCayaBNbwfXNt1w3/I/sWCyqaUKAQ/waPe6QUAGWPHg2fGctGMfhi6HbFk9LG5LG8luwVxvmFfhmXEsIILdH1jasOMctzCiMvttpHxY2gKMVX4OJ/Pt8TB7EhPmXDxu3WEBkqyulcQydBb3GpV6QOX5BWWaJxw9WnLRaCXFKMQOBLgx5tQcbaDmsbDk5dWgQeUcHCXRCks+8p329iCHAl"
    maven_repository: "{{ jenkins_home }}/.repository"
    gcc_version: "4:4.8.2-1ubuntu6"
    cppunit_version: "1.13-0"
    boost_version: "1.54"
    
