---

- name: Apply common configuration to all nodes
  hosts: common
  gather_facts: false
  remote_user: root

  roles:
    - albanandrieu.ansible_common

  vars:
     apt_notification_email: "alban.andrieu@free.fr"
     apt_upgrade_system_enabled: no
