---

- name: Install nodejs
  hosts: nodejs
  #remote_user: root
  become: true

  roles:
    - geerlingguy.nodejs

  vars:
       #nodejs_install_packages: false
       #nodejs_global_packages: []
       nodejs_global_packages:
         - angular@1.3.15
         - bower@1.8.8
         - casperjs@1.1.4
         - coffee-script@1.10.0
         - connect@1.9.2
         - grunt-cli@1.3.2
         - jshint@2.9.5
         - jsonlint@1.6.2
         - json2csv@4.3.3
         - nsp@3.2.1
         - phantomjs-prebuilt@2.1.16
         - phantomas@1.20.1
         - slimerjs@0.10.3
         - tap-eater@0.0.3
         - webdriver-manager@12.1.7
         - yarn@1.19.1
         - yo@3.1.1
         - shrinkwrap@0.4.0
         - newman@4.5.5
         - xunit-viewer@5.1.11
         - dockerfile_lint@0.3.3
