---

- name: Install selenium
  hosts: jenkins-slaves
  become: true

  roles:
    - albanandrieu.selenium

  vars:
    #selenium_mirror: "http://albandrieu.com/download/selenium/"
    selenium_server_major_version: "2.42"
    selenium_server_minor_version: "2"
    docker_files_enable: no
