---
# This workflow will build a Docker image

name: Docker CI

true:
  push:
    branches: [master, main]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [master, main]
    paths-ignore:
      - "**.md"

jobs:
  build-docker:
    if: github.actor != 'dependabot[bot]' && github.actor!= 'dependabot-preview[bot]' # ignore the pull request which comes from user dependabot.
    name: Build Docker
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-latest
    # See https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
    # runs-on: ubuntu-latest
    # container:
    #   image: nabla/ansible-jenkins-slave-docker:1.0.16
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: adopt

      # Runs a single command using the runners shell
      - name: Install Node.Js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install bower
        run: npm install -g markdown-toc@latest secretlint@latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            ANSIBLE_VAULT_PASSWORD=${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          #            --squash
          #  tags: nabla/ansible-jenkins-slave-docker:latest,nabla/ansible-jenkins-slave-docker:${{ github.sha }}
          tags: nabla/ansible-jenkins-slave-docker:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: nabla/ansible-jenkins-slave-docker:latest
          format: template
          template: "@/contrib/sarif.tpl"
          output: trivy-results.sarif
          #  format: 'table'
          #  exit-code: '1'
          ignore-unfixed: true
          skip-dirs: .direnv
          skip-files: Gemfile.lock,Pipfile.lock,package-lock.json,requirements.txt,docker/ubuntu16/Dockerfile,docker/ubuntu18/Dockerfile
          security-checks: vuln # vuln,secret
          vuln-type: os,library
          severity: CRITICAL,HIGH

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif
