# vi: ft=yaml.ansible.jinja2
---
name: MegaLinter

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-mega-linter:
    if: >-
      (github.event_name != 'pull_request' || github.event.pull_request.draft == false) &&
      github.actor != 'dependabot[bot]' &&
      github.actor != 'dependabot-preview[bot]'
    name: Mega Linter
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter@a7b1a3af0f3bd4de4db855969d27e224005665a6 # v7.1.0
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive production artifacts
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: MegaLinter reports
          path: |
            report
            mega-linter.log
