---
# .github/workflows/version.yml
name: Git Version

true:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }} # checkout the correct branch name
          fetch-depth: 00 # fetch the whole repo history

      - name: Git Version
        uses: codacy/git-version@2.8.0
